/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Clemens
 */
public class AddPreferenceDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddPreferenceDialog
     */
    public AddPreferenceDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Add Preference");
        cbCourseEvent.addActionListener(new MyActionListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbCourseEvent = new javax.swing.JComboBox(beans.LectureData.values());
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner(new SpinnerDateModel());
        jLabel5 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner(new SpinnerDateModel());
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));

        jPanel1.setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setText("Course/Event");
        jPanel1.add(jLabel1);

        /*
        cbCourseEvent.setModel(null);
        */
        jPanel1.add(cbCourseEvent);

        jLabel2.setText("Room:");
        jPanel1.add(jLabel2);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jTextField2.setEnabled(false);
        jPanel4.add(jTextField2, java.awt.BorderLayout.CENTER);

        jButton4.setText("...");
        jPanel4.add(jButton4, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.setBorder(BorderFactory.createTitledBorder("Start Date"));

        jTextField3.setEnabled(false);
        jTextField3.setFocusable(false);
        jPanel5.add(jTextField3, java.awt.BorderLayout.CENTER);

        try{
            Image img = ImageIO.read(getClass().getResource("../resources/calendar-icon.png"));
            Image resizedImage = img.getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
            jButton5.setIcon(new ImageIcon(resizedImage));
        }catch(IOException ex)
        {
        }
        jPanel5.add(jButton5, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel5);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jTextField1.setEditable(false);
        jTextField1.setEnabled(false);
        jTextField1.setFocusable(false);
        jPanel3.add(jTextField1, java.awt.BorderLayout.CENTER);

        try{
            Image img = ImageIO.read(getClass().getResource("../resources/calendar-icon.png"));
            Image resizedImage = img.getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
            jButton3.setIcon(new ImageIcon(resizedImage));
        }catch(IOException ex)
        {
        }
        jPanel3.add(jButton3, java.awt.BorderLayout.LINE_END);

        jPanel3.setBorder(BorderFactory.createTitledBorder("End Date"));

        jPanel1.add(jPanel3);

        jLabel4.setText("Start Time:");
        jPanel1.add(jLabel4);

        JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(jSpinner1, "HH:mm");
        jSpinner1.setEditor(timeEditor);
        jPanel1.add(jSpinner1);

        jLabel5.setText("End Time:");
        jPanel1.add(jLabel5);

        JSpinner.DateEditor timeEditor2 = new JSpinner.DateEditor(jSpinner2, "HH:mm");
        jSpinner2.setEditor(timeEditor2);
        jPanel1.add(jSpinner2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private class MyActionListener implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            changeGUI();
        }
        private void changeGUI()
        {
            if (cbCourseEvent.getSelectedItem().toString().equals("Course"))
            {
                jPanel3.setVisible(true);
                jPanel5.setBorder(BorderFactory.createTitledBorder("Start Date"));
            }

            else
            {
                jPanel3.setVisible(false);
                jPanel5.setBorder(BorderFactory.createTitledBorder("Date"));
            }

        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPreferenceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPreferenceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPreferenceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPreferenceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddPreferenceDialog dialog = new AddPreferenceDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbCourseEvent;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
