/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import intellicourse.entity.User;
import intellicourse.util.HibernateUtil;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import org.hibernate.SQLQuery;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.transform.Transformers;
import org.hibernate.type.IntegerType;

/**
 *
 * @author Sandra
 */
public class AdminDialog extends javax.swing.JDialog {

    /**
     * Creates new form EditAdminDialog
     */
    public AdminDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Admin");
        
        filterVorname.getDocument().addDocumentListener(new MyDocumentListener());
        filterNachname.getDocument().addDocumentListener(new MyDocumentListener());
        filterUser.getDocument().addDocumentListener(new MyDocumentListener());
        displayData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        filterUser = new javax.swing.JTextField();
        filterVorname = new javax.swing.JTextField();
        filterNachname = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        showadminTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        Addbtn = new javax.swing.JToggleButton();
        EditBtn = new javax.swing.JToggleButton();
        Deletebtn = new javax.swing.JToggleButton();
        Okbtn = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(2, 3));

        jLabel2.setText("Username");
        jPanel1.add(jLabel2);

        jLabel3.setText("Vorname:");
        jPanel1.add(jLabel3);

        jLabel4.setText("Nachname");
        jPanel1.add(jLabel4);

        filterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterUserActionPerformed(evt);
            }
        });
        jPanel1.add(filterUser);
        jPanel1.add(filterVorname);
        jPanel1.add(filterNachname);

        showadminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(showadminTable);

        jPanel5.setLayout(new java.awt.GridLayout(1, 4));

        Addbtn.setText("Add");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });
        jPanel5.add(Addbtn);

        EditBtn.setText("Edit");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });
        jPanel5.add(EditBtn);

        Deletebtn.setText("Delete");
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });
        jPanel5.add(Deletebtn);

        Okbtn.setText("Ok");
        Okbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkbtnActionPerformed(evt);
            }
        });
        jPanel5.add(Okbtn);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jMenu1.setText("log out");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void filterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterUserActionPerformed

    private void OkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkbtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_OkbtnActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        // TODO add your handling code here:
        AddAdminDialog aa = new AddAdminDialog(null, rootPaneCheckingEnabled);
        aa.addWindowListener(new MyWindowAdapter());
        aa.setisAdd(true);
        aa.setTitle("Add Admin");
        aa.setVisible(true);
        
    }//GEN-LAST:event_AddbtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
        AddAdminDialog aa = new AddAdminDialog(null, rootPaneCheckingEnabled);
        aa.setTitle("Edit Teachinng Staff");
        int rowindex = showadminTable.getSelectedRow();
        int id = Integer.parseInt(showadminTable.getValueAt(rowindex, 0).toString());
        String username = showadminTable.getValueAt(rowindex, 1).toString();
        String  password= showadminTable.getValueAt(rowindex, 4).toString();
        String vorname = showadminTable.getValueAt(rowindex, 2).toString();
        String nachname = showadminTable.getValueAt(rowindex, 3).toString();
        User user = new User(id,username,password,vorname,nachname);
        aa.setAdmin(user);
        aa.setisAdd(false);
        aa.fillFields();
        aa.setVisible(true);
        displayData();
        
        
    }//GEN-LAST:event_EditBtnActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        // TODO add your handling code here:
        int rowindex = showadminTable.getSelectedRow();
        int id = Integer.parseInt(showadminTable.getValueAt(rowindex, 0).toString());
        
        if (id == 1){
            JOptionPane.showMessageDialog(null, "Could not delete master admin.");
        }
        else {
            try {
                Session session = HibernateUtil.getSessionFactory().openSession();
                session.beginTransaction();
                String sql = "DELETE FROM admin WHERE uid=" + id;
                SQLQuery query = session.createSQLQuery(sql);
                query.executeUpdate();
                sql = "DELETE FROM user WHERE uid=" + id;
                query = session.createSQLQuery(sql);
                query.executeUpdate();
                session.getTransaction().commit();
                session.close();
                displayData();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error: " + e);
            }  
        }
    }//GEN-LAST:event_DeletebtnActionPerformed

    
    private void displayData() {
        String sql;
        if (filterUser.getText().trim().equals("") && filterVorname.getText().trim().equals("") && filterNachname.getText().trim().equals("")) {
            sql = "select u.uid, u.username, u.password, u.vorname, u.nachname from  User  u inner join admin s USING(uid)";
        } else
            sql = "select u.uid, u.username, u.password, u.vorname, u.nachname from  User  u inner join admin a USING(uid) "
                    + "WHERE UPPER(u.username) LIKE '" + filterUser.getText().trim().toUpperCase() + "%' "
                    + "AND UPPER(u.vorname) LIKE '" + filterVorname.getText().trim().toUpperCase() + "%' "
                    + "AND UPPER(u.nachname) LIKE '" + filterNachname.getText().trim().toUpperCase() + "%'";
        
        executeQuery(sql);
    }
    
    private void executeQuery(String query) {
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            SQLQuery q = session.createSQLQuery(query);
            q.addScalar("uid",new IntegerType());
            q.addScalar("username",new org.hibernate.type.StringType());
            q.addScalar("vorname",new org.hibernate.type.StringType());
            q.addScalar("nachname",new org.hibernate.type.StringType());
            q.addScalar("password",new org.hibernate.type.StringType());
            q.setResultTransformer(Transformers.aliasToBean(User.class));
            List<User> resultList = q.list();
            displayResult(resultList);
            session.getTransaction().commit();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void displayResult(List resultList) {
        Vector<String> tableHead = new Vector<>();
        Vector tableData = new Vector();
        tableHead.add("uid");
        tableHead.add("Username");
        tableHead.add("First Name");
        tableHead.add("Last Name");
        tableHead.add("Password");
        
        for (Object o : resultList) {
            User user = new User();
            
            User u = (User) o;
            Vector<Object> row = new Vector<>();
            row.add(u.getUid());
            row.add(u.getUsername());
            row.add(u.getVorname());
            row.add(u.getNachname());
            row.add(u.getPassword());
            tableData.add(row);
        }
        showadminTable.setModel(new DefaultTableModel(tableData, tableHead));

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminDialog dialog = new AdminDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Addbtn;
    private javax.swing.JToggleButton Deletebtn;
    private javax.swing.JToggleButton EditBtn;
    private javax.swing.JToggleButton Okbtn;
    private javax.swing.JTextField filterNachname;
    private javax.swing.JTextField filterUser;
    private javax.swing.JTextField filterVorname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable showadminTable;
    // End of variables declaration//GEN-END:variables

    
    private  class MyWindowAdapter extends WindowAdapter {

        @Override
        public void windowDeactivated(WindowEvent e) {
            AdminDialog.this.displayData();
        }

        @Override
        public void windowClosed(WindowEvent e) {
            AdminDialog.this.displayData();
        }

        @Override
        public void windowClosing(WindowEvent e) {
            AdminDialog.this.displayData();
        }
        
    }
    
    private class MyDocumentListener implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            AdminDialog.this.displayData();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            AdminDialog.this.displayData();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            AdminDialog.this.displayData();
        }
    }
    
    
}

