/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import intellicourse.entity.Course;
import intellicourse.entity.Lecture;
import intellicourse.util.HibernateUtil;
import java.util.List;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.ListSelectionModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import org.hibernate.SQLQuery;
import org.hibernate.Session;
import org.hibernate.transform.Transformers;
import org.hibernate.type.IntegerType;
import org.hibernate.type.StringType;

/**
 *
 * @author Clemens
 */
public class ChooseCourseEventDialog extends javax.swing.JDialog {
    private boolean isCourse = true;
    private boolean fromPreference = true;
    private Lecture result = null;
    private List<Lecture> resultList = null;
    

    public void setIsCourse(boolean isCourse) {
        this.isCourse = isCourse;
    }
    /**
     * Creates new form ChooseCourseEventDialog
     */
    public ChooseCourseEventDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        this.setLocationRelativeTo(null);
        tbAnzeigeCourse.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tfName.getDocument().addDocumentListener(new ChooseCourseEventDialog.MyDocumentListener());
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbAnzeigeCourse = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tfName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(tbAnzeigeCourse);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout());

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.setBorder(BorderFactory.createTitledBorder("Filter by Name"));
        jPanel2.add(tfName, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i = tbAnzeigeCourse.getSelectedRow();
        result = resultList.get(i);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseCourseEventDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseCourseEventDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseCourseEventDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseCourseEventDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChooseCourseEventDialog dialog = new ChooseCourseEventDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
    
    private void displayData() {
        String sql;
        
        if (isCourse && fromPreference)
        {
        sql = "select l.lid, l.name, l.beschreibung from Lecture as l INNER JOIN course USING(lid) "
                + "WHERE UPPER(l.name) LIKE '" + tfName.getText().trim().toUpperCase() + "%' "
                + "AND rid IS NULL";
        }
        else if (!isCourse && fromPreference)
        {
            sql = "select l.lid, l.name, l.beschreibung from Lecture as l INNER JOIN event USING(lid) "
                + "WHERE UPPER(l.name) LIKE '" + tfName.getText().trim().toUpperCase() + "%' "
                    + "AND rid IS NULL";
        } 
        else if (isCourse && !fromPreference)
        {
            sql = "select l.lid, l.name, l.beschreibung from Lecture as l INNER JOIN course USING(lid) "
                + "WHERE UPPER(l.name) LIKE '" + tfName.getText().trim().toUpperCase() + "%' "
                    + "AND preference = 1 OR "
                    + "rid IS NULL";
        }
        else
        {
            sql = "select l.lid, l.name, l.beschreibung from Lecture as l INNER JOIN event USING(lid) "
                + "WHERE UPPER(l.name) LIKE '" + tfName.getText().trim().toUpperCase() + "%' "
                    + "AND preference = 1 OR "
                    + "rid IS NULL";
        }
        executeQuery(sql);
    }

    private void executeQuery(String query) {
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            SQLQuery q = session.createSQLQuery(query);
            q.addScalar("lid",new IntegerType());
            q.addScalar("name",new StringType());
            q.addScalar("beschreibung",new StringType());
            q.setResultTransformer(Transformers.aliasToBean(Lecture.class));
            resultList = q.list();
            displayResult(resultList);
            session.getTransaction().commit();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void displayResult(List resultList) {
        Vector<String> tableHead = new Vector<String>();
        Vector tableData = new Vector();
        tableHead.add("Lid");
        tableHead.add("Name");
        tableHead.add("Beschreibung");
        
        for (Object o : resultList) {
            Lecture lecture = new Lecture();
            
            Lecture l = (Lecture) o;
            Vector<Object> row = new Vector<>();
            row.add(l.getLid());
            row.add(l.getName());
            row.add(l.getBeschreibung());           
            tableData.add(row);
        }
        tbAnzeigeCourse.setModel(new DefaultTableModel(tableData, tableHead));

    }
    
        public Lecture showCourseDialog(boolean fromPreference)
        {
            this.fromPreference = fromPreference;
            this.displayData();
            this.setVisible(true);
            return result;
        }
    
        private class MyDocumentListener implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            ChooseCourseEventDialog.this.displayData();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            ChooseCourseEventDialog.this.displayData();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            ChooseCourseEventDialog.this.displayData();
        }

        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAnzeigeCourse;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
