package intellicourse.entity;
// Generated 08.12.2015 10:38:01 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CourseDayTime generated by hbm2java
 */
@Entity
@Table(name="course_day_time"
    ,catalog="oad_db"
)
public class CourseDayTime  implements java.io.Serializable {


     private int lid;
     private Course course;
     private Date day;
     private Date von;
     private Date bis;

    public CourseDayTime() {
    }

	
    public CourseDayTime(Course course) {
        this.course = course;
    }
    public CourseDayTime(Course course, Date day, Date von, Date bis) {
       this.course = course;
       this.day = day;
       this.von = von;
       this.bis = bis;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="course"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="lid", unique=true, nullable=false)
    public int getLid() {
        return this.lid;
    }
    
    public void setLid(int lid) {
        this.lid = lid;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="day", length=10)
    public Date getDay() {
        return this.day;
    }
    
    public void setDay(Date day) {
        this.day = day;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="von", length=8)
    public Date getVon() {
        return this.von;
    }
    
    public void setVon(Date von) {
        this.von = von;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="bis", length=8)
    public Date getBis() {
        return this.bis;
    }
    
    public void setBis(Date bis) {
        this.bis = bis;
    }




}


