package intellicourse.entity;
// Generated 30.11.2015 15:40:21 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name="course"
    ,catalog="oad_db"
)
public class Course  implements java.io.Serializable {


     private int lid;
     private Lecture lecture;
     private int kursnr;
     private Date startDat;
     private Date endDat;

    public Course() {
    }

    public Course(Lecture lecture) {
       this.lecture = lecture;
    }
    public Course(Lecture lecture, int kursnr, Date startDat, Date endDat) {
       this.lecture = lecture;
       this.kursnr = kursnr;
       this.startDat = startDat;
       this.endDat = endDat;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="lecture"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="lid", unique=true, nullable=false)
    public int getLid() {
        return this.lid;
    }
    
    public void setLid(int lid) {
        this.lid = lid;
    }

@OneToOne(fetch=FetchType.LAZY, orphanRemoval = true)@PrimaryKeyJoinColumn
    public Lecture getLecture() {
        return this.lecture;
    }
    
    public void setLecture(Lecture lecture) {
        this.lecture = lecture;
    }

    
    @Column(name="kursnr", nullable=true)
    public int getKursnr() {
        return this.kursnr;
    }
    
    public void setKursnr(int kursnr) {
        this.kursnr = kursnr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="startDat", length=10)
    public Date getStartDat() {
        return this.startDat;
    }
    
    public void setStartDat(Date startDat) {
        this.startDat = startDat;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="endDat", length=10)
    public Date getEndDat() {
        return this.endDat;
    }
    
    public void setEndDat(Date endDat) {
        this.endDat = endDat;
    }




}


