package intellicourse.entity;
// Generated 29.11.2015 23:06:33 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private int lid;
     private Lecture lecture;
     private int kursnr;
     private Date startDat;
     private Date endDat;

    public Course() {
    }

    public Course(Lecture lecture, int kursnr, Date startDat, Date endDat) {
       this.lecture = lecture;
       this.kursnr = kursnr;
       this.startDat = startDat;
       this.endDat = endDat;
    }
   
    public int getLid() {
        return this.lid;
    }
    
    public void setLid(int lid) {
        this.lid = lid;
    }
    public Lecture getLecture() {
        return this.lecture;
    }
    
    public void setLecture(Lecture lecture) {
        this.lecture = lecture;
    }
    public int getKursnr() {
        return this.kursnr;
    }
    
    public void setKursnr(int kursnr) {
        this.kursnr = kursnr;
    }
    public Date getStartDat() {
        return this.startDat;
    }
    
    public void setStartDat(Date startDat) {
        this.startDat = startDat;
    }
    public Date getEndDat() {
        return this.endDat;
    }
    
    public void setEndDat(Date endDat) {
        this.endDat = endDat;
    }




}


