package intellicourse.entity;
// Generated 08.12.2015 10:38:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Curriculum generated by hbm2java
 */
@Entity
@Table(name="curriculum"
    ,catalog="oad_db"
)
public class Curriculum  implements java.io.Serializable {


     private Integer cid;
     private String name;
     private Set lectures = new HashSet(0);

    public Curriculum() {
    }

	
    public Curriculum(String name) {
        this.name = name;
    }
    public Curriculum(String name, Set lectures) {
       this.name = name;
       this.lectures = lectures;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cid", unique=true, nullable=false)
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="curriculum_lecture", catalog="oad_db", joinColumns = { 
        @JoinColumn(name="cid", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="lid", nullable=false, updatable=false) })
    public Set getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Set lectures) {
        this.lectures = lectures;
    }




}


