package intellicourse.entity;
// Generated 30.11.2015 15:40:21 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name="event"
    ,catalog="oad_db"
)
public class Event  implements java.io.Serializable {


     private int lid;
     private Lecture lecture;
     private int eventnr;
     private Date datum;

    public Event() {
    }

    public Event(Lecture lecture, int eventnr, Date datum) {
       this.lecture = lecture;
       this.eventnr = eventnr;
       this.datum = datum;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="lecture"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="lid", unique=true, nullable=false)
    public int getLid() {
        return this.lid;
    }
    
    public void setLid(int lid) {
        this.lid = lid;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Lecture getLecture() {
        return this.lecture;
    }
    
    public void setLecture(Lecture lecture) {
        this.lecture = lecture;
    }

    
    @Column(name="eventnr", nullable=false)
    public int getEventnr() {
        return this.eventnr;
    }
    
    public void setEventnr(int eventnr) {
        this.eventnr = eventnr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datum", nullable=false, length=10)
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }




}


