package intellicourse.entity;
// Generated 29.11.2015 23:06:33 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private int lid;
     private Lecture lecture;
     private int eventnr;
     private Date datum;

    public Event() {
    }

    public Event(Lecture lecture, int eventnr, Date datum) {
       this.lecture = lecture;
       this.eventnr = eventnr;
       this.datum = datum;
    }
   
    public int getLid() {
        return this.lid;
    }
    
    public void setLid(int lid) {
        this.lid = lid;
    }
    public Lecture getLecture() {
        return this.lecture;
    }
    
    public void setLecture(Lecture lecture) {
        this.lecture = lecture;
    }
    public int getEventnr() {
        return this.eventnr;
    }
    
    public void setEventnr(int eventnr) {
        this.eventnr = eventnr;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }




}


