package intellicourse.entity;
// Generated 29.11.2015 23:06:33 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lecture generated by hbm2java
 */
public class Lecture  implements java.io.Serializable {


     private Integer lid;
     private Room room;
     private Staff staff;
     private String name;
     private String beschreibung;
     private Date von;
     private Date bis;
     private Event event;
     private Course course;
     private Set students = new HashSet(0);

    public Lecture() {
    }

	
    public Lecture(Room room, Staff staff, String name, String beschreibung, Date von, Date bis) {
        this.room = room;
        this.staff = staff;
        this.name = name;
        this.beschreibung = beschreibung;
        this.von = von;
        this.bis = bis;
    }
    public Lecture(Room room, Staff staff, String name, String beschreibung, Date von, Date bis, Event event, Course course, Set students) {
       this.room = room;
       this.staff = staff;
       this.name = name;
       this.beschreibung = beschreibung;
       this.von = von;
       this.bis = bis;
       this.event = event;
       this.course = course;
       this.students = students;
    }
   
    public Integer getLid() {
        return this.lid;
    }
    
    public void setLid(Integer lid) {
        this.lid = lid;
    }
    public Room getRoom() {
        return this.room;
    }
    
    public void setRoom(Room room) {
        this.room = room;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBeschreibung() {
        return this.beschreibung;
    }
    
    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }
    public Date getVon() {
        return this.von;
    }
    
    public void setVon(Date von) {
        this.von = von;
    }
    public Date getBis() {
        return this.bis;
    }
    
    public void setBis(Date bis) {
        this.bis = bis;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }




}


