package intellicourse.entity;
// Generated 29.11.2015 23:06:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Room generated by hbm2java
 */
public class Room  implements java.io.Serializable {


     private Integer rid;
     private String name;
     private int anzSitzplatz;
     private Set lectures = new HashSet(0);

    public Room() {
    }

	
    public Room(String name, int anzSitzplatz) {
        this.name = name;
        this.anzSitzplatz = anzSitzplatz;
    }
    public Room(String name, int anzSitzplatz, Set lectures) {
       this.name = name;
       this.anzSitzplatz = anzSitzplatz;
       this.lectures = lectures;
    }
   
    public Integer getRid() {
        return this.rid;
    }
    
    public void setRid(Integer rid) {
        this.rid = rid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getAnzSitzplatz() {
        return this.anzSitzplatz;
    }
    
    public void setAnzSitzplatz(int anzSitzplatz) {
        this.anzSitzplatz = anzSitzplatz;
    }
    public Set getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Set lectures) {
        this.lectures = lectures;
    }




}


