package intellicourse.entity;
// Generated 08.12.2015 10:38:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name="room"
    ,catalog="oad_db"
)
public class Room  implements java.io.Serializable {


     private Integer rid;
     private String name;
     private int anzSitzplatz;
     private Set lectures = new HashSet(0);

    public Room() {
    }

    public Room(Integer rid, String name, int anzSitzplatz)
    {
        this.rid = rid;
        this.name = name;
        this.anzSitzplatz = anzSitzplatz;
        
    }

    public Room(Integer rid) {
        this.rid = rid;
    }
    
    
    public Room(String name, int anzSitzplatz) {
        this.name = name;
        this.anzSitzplatz = anzSitzplatz;
    }
    public Room(String name, int anzSitzplatz, Set lectures) {
       this.name = name;
       this.anzSitzplatz = anzSitzplatz;
       this.lectures = lectures;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rid", unique=true, nullable=false)
    public Integer getRid() {
        return this.rid;
    }
    
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="anzSitzplatz", nullable=false)
    public int getAnzSitzplatz() {
        return this.anzSitzplatz;
    }
    
    public void setAnzSitzplatz(int anzSitzplatz) {
        this.anzSitzplatz = anzSitzplatz;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="room")
    public Set getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Set lectures) {
        this.lectures = lectures;
    }




}


