package intellicourse.entity;
// Generated 30.11.2015 15:40:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
    ,catalog="oad_db"
)
public class Student  implements java.io.Serializable {


     private int uid;
     private User user;
     private String adresse;
     private int matnr;
     private int aktSemester;
     private Set lectures = new HashSet(0);

    public Student() {
    }

	
    public Student(User user, String adresse, int matnr, int aktSemester) {
        this.user = user;
        this.adresse = adresse;
        this.matnr = matnr;
        this.aktSemester = aktSemester;
    }
    public Student(User user, String adresse, int matnr, int aktSemester, Set lectures) {
       this.user = user;
       this.adresse = adresse;
       this.matnr = matnr;
       this.aktSemester = aktSemester;
       this.lectures = lectures;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="user"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="uid", unique=true, nullable=false)
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }

@OneToOne(fetch=FetchType.LAZY, orphanRemoval = true)@PrimaryKeyJoinColumn
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="adresse", nullable=false, length=200)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="matnr", nullable=false)
    public int getMatnr() {
        return this.matnr;
    }
    
    public void setMatnr(int matnr) {
        this.matnr = matnr;
    }

    
    @Column(name="akt_semester", nullable=false)
    public int getAktSemester() {
        return this.aktSemester;
    }
    
    public void setAktSemester(int aktSemester) {
        this.aktSemester = aktSemester;
    }

@ManyToMany(fetch=FetchType.LAZY, cascade={CascadeType.DETACH, CascadeType.MERGE, CascadeType.REFRESH, CascadeType.PERSIST}, mappedBy="students")
    public Set getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Set lectures) {
        this.lectures = lectures;
    }




}


