package intellicourse.entity;
// Generated 29.11.2015 23:06:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int uid;
     private User user;
     private String adresse;
     private int matnr;
     private int aktSemester;
     private Set lectures = new HashSet(0);

    public Student() {
    }

	
    public Student(User user, String adresse, int matnr, int aktSemester) {
        this.user = user;
        this.adresse = adresse;
        this.matnr = matnr;
        this.aktSemester = aktSemester;
    }
    public Student(User user, String adresse, int matnr, int aktSemester, Set lectures) {
       this.user = user;
       this.adresse = adresse;
       this.matnr = matnr;
       this.aktSemester = aktSemester;
       this.lectures = lectures;
    }
   
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public int getMatnr() {
        return this.matnr;
    }
    
    public void setMatnr(int matnr) {
        this.matnr = matnr;
    }
    public int getAktSemester() {
        return this.aktSemester;
    }
    
    public void setAktSemester(int aktSemester) {
        this.aktSemester = aktSemester;
    }
    public Set getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Set lectures) {
        this.lectures = lectures;
    }




}


