package intellicourse.entity;
// Generated 29.11.2015 23:06:33 by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer uid;
     private String username;
     private String password;
     private String vorname;
     private String nachname;
     private Staff staff;
     private Admin admin;
     private Student student;

    public User() {
    }

	
    public User(String username, String password, String vorname, String nachname) {
        this.username = username;
        this.password = password;
        this.vorname = vorname;
        this.nachname = nachname;
    }
    public User(String username, String password, String vorname, String nachname, Staff staff, Admin admin, Student student) {
       this.username = username;
       this.password = password;
       this.vorname = vorname;
       this.nachname = nachname;
       this.staff = staff;
       this.admin = admin;
       this.student = student;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getVorname() {
        return this.vorname;
    }
    
    public void setVorname(String vorname) {
        this.vorname = vorname;
    }
    public String getNachname() {
        return this.nachname;
    }
    
    public void setNachname(String nachname) {
        this.nachname = nachname;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }




}


