package intellicourse.entity;
// Generated 30.11.2015 15:40:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="oad_db"
)
public class User  implements java.io.Serializable {


     private Integer uid;
     private String username;
     private String password;
     private String vorname;
     private String nachname;
     private Staff staff;
     private Admin admin;
     private Student student;

    public User() {
    }

	
    public User(String username, String password, String vorname, String nachname) {
        this.username = username;
        this.password = password;
        this.vorname = vorname;
        this.nachname = nachname;
    }
    public User(String username, String password, String vorname, String nachname, Staff staff, Admin admin, Student student) {
       this.username = username;
       this.password = password;
       this.vorname = vorname;
       this.nachname = nachname;
       this.staff = staff;
       this.admin = admin;
       this.student = student;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="uid", unique=true, nullable=false)
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    
    @Column(name="username", nullable=false, length=30)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=30)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="vorname", nullable=false, length=50)
    public String getVorname() {
        return this.vorname;
    }
    
    public void setVorname(String vorname) {
        this.vorname = vorname;
    }

    
    @Column(name="nachname", nullable=false, length=50)
    public String getNachname() {
        return this.nachname;
    }
    
    public void setNachname(String nachname) {
        this.nachname = nachname;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="user")
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="user")
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="user")
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }




}


